VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ITheme"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit

''
' Description here
'
'@/

'@================================================================================
' Interfaces
'@================================================================================

'@================================================================================
' Events
'@================================================================================

'@================================================================================
' Enums
'@================================================================================

'@================================================================================
' Types
'@================================================================================

'@================================================================================
' Constants
'@================================================================================

Private Const ModuleName                            As String = "ITheme"

'@================================================================================
' Member variables
'@================================================================================

'@================================================================================
' Class Event Handlers
'@================================================================================

'@================================================================================
' XXXX Interface Members
'@================================================================================

'@================================================================================
' XXXX Event Handlers
'@================================================================================

'@================================================================================
' Properties
'@================================================================================

Public Property Get AlertForeColor() As OLE_COLOR
End Property

Public Property Get AlertFont() As StdFont
End Property

Public Property Get Appearance() As AppearanceSettings
End Property

Public Property Get BackColor() As OLE_COLOR
End Property

Public Property Get BackColorAsk() As OLE_COLOR
End Property

Public Property Get BackColorBid() As OLE_COLOR
End Property

Public Property Get BackColorTrade() As OLE_COLOR
End Property

Public Property Get BaseColor() As OLE_COLOR
End Property

Public Property Get BaseFont() As StdFont
End Property

Public Property Get BorderStyle() As BorderStyleSettings
End Property

Public Property Get ButtonBackColor() As OLE_COLOR
End Property

Public Property Get ButtonFont() As StdFont
End Property

Public Property Get ButtonForeColor() As OLE_COLOR
End Property

Public Property Get ComboFont() As StdFont
End Property

Public Property Get CoolbarBackColor() As OLE_COLOR
End Property

Public Property Get DecreasedValueColor() As OLE_COLOR
End Property

Public Property Get DefaultBorderColor() As OLE_COLOR
End Property

Public Property Get DisabledBackColor() As OLE_COLOR
End Property

Public Property Get DisabledFont() As StdFont
End Property

Public Property Get DisabledForeColor() As OLE_COLOR
End Property

Public Property Get FocusBorderColor() As OLE_COLOR
End Property

Public Property Get ForeColor() As OLE_COLOR
End Property

Public Property Get ForeColorAsk() As OLE_COLOR
End Property

Public Property Get ForeColorBid() As OLE_COLOR
End Property

Public Property Get ForeColorTrade() As OLE_COLOR
End Property

Public Property Get GridBackColorFixed() As OLE_COLOR
End Property

Public Property Get GridFont() As StdFont
End Property

Public Property Get GridFontFixed() As StdFont
End Property

Public Property Get GridForeColor() As OLE_COLOR
End Property

Public Property Get GridForeColorFixed() As OLE_COLOR
End Property

Public Property Get GridLineColor() As OLE_COLOR
End Property

Public Property Get GridLineColorFixed() As OLE_COLOR
End Property

Public Property Get GridRowBackColorEven() As OLE_COLOR
End Property

Public Property Get GridRowBackColorOdd() As OLE_COLOR
End Property

Public Property Get GridRowForeColorEven() As OLE_COLOR
End Property

Public Property Get GridRowForeColorOdd() As OLE_COLOR
End Property

Public Property Get IncreasedValueColor() As OLE_COLOR
End Property

Public Property Get MouseOverBackColor() As OLE_COLOR
End Property

Public Property Get MouseOverFont() As StdFont
End Property

Public Property Get MouseOverForeColor() As OLE_COLOR
End Property

Public Property Get NegativeChangeBackColor() As OLE_COLOR
End Property

Public Property Get NegativeChangeForeColor() As OLE_COLOR
End Property

Public Property Get NonDefaultBorderColor() As OLE_COLOR
End Property

Public Property Get PositiveChangeBackColor() As OLE_COLOR
End Property

Public Property Get PositiveChangeForeColor() As OLE_COLOR
End Property

Public Property Get PushedBackColor() As OLE_COLOR
End Property

Public Property Get PushedFont() As StdFont
End Property

Public Property Get PushedForeColor() As OLE_COLOR
End Property

Public Property Get StatusBarBackColor() As OLE_COLOR
End Property

Public Property Get StatusBarForeColor() As OLE_COLOR
End Property

Public Property Get TabstripBackColor() As OLE_COLOR
End Property

Public Property Get TabstripForeColor() As OLE_COLOR
End Property

Public Property Get TextBackColor() As OLE_COLOR
End Property

Public Property Get TextForeColor() As OLE_COLOR
End Property

Public Property Get TextFont() As StdFont
End Property

Public Property Get ToolbarBackColor() As OLE_COLOR
End Property

'@================================================================================
' Methods
'@================================================================================

'@================================================================================
' Helper Functions
'@================================================================================




